config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:  # dev mode only
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]  # /

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models
from cal import Calendar


class AbstractItem(core_models.AbstractTimeStampModel):
    """
    Abstract Item
    """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """
    RoomType Model Definition
    """

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):
    """
    Amenity Model Definition
    """

    class Meta:
        verbose_name_plural = "Amenties"


class Facility(AbstractItem):
    """
    Facility Model Definition
    """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """
    HouseRule Model Definition
    """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.AbstractTimeStampModel):
    """
    Photo Model Definition
    """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.AbstractTimeStampModel):
    """
    Room Model Definition
    """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facilities = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):  # override save method
        self.city = str.capitalize(self.city)  # abc -> Abc
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def get_total_rating(self):
        all_reviews = self.reviews.all()
        all_reviews_size = len(all_reviews)
        if all_reviews_size:
            all_ratings = 0
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round((all_ratings / all_reviews_size), 1)
        return 0

    get_total_rating.short_description = "Total Rating"

    def get_first_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    """ SearchForm Definition """

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="US").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    """ CreatePhotoForm Definition """

    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, UpdateView, FormView, View
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):
    """
    HomeView Definition
    """

    model = models.Room
    context_object_name = "rooms"
    paginate_by = 8
    paginate_orphans = 1
    ordering = "created"


class RoomDetail(DetailView):
    """
    RoomDetail Definition
    """

    model = models.Room


class SearchView(View):
    """
    SearchView Definition
    """

    def get(self, request):
        country = request.GET.get("country")
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}
                if city != "Anywhere":
                    filter_args["city__startswith"] = city
                filter_args["country"] = country
                if room_type is not None:
                    filter_args["room_type"] = room_type
                if price is not None:
                    filter_args["price__lte"] = price
                if guests is not None:
                    filter_args["guests__gte"] = guests
                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms
                if beds is not None:
                    filter_args["beds__gte"] = beds
                if baths is not None:
                    filter_args["baths__gte"] = baths
                if instant_book is True:
                    filter_args["instant_book"] = True
                if superhost is True:
                    filter_args["host__superhost"] = True
                qs = models.Room.objects.filter(**filter_args).order_by("-created")
                if amenities is not None:
                    for amenity in amenities:
                        qs = qs.filter(amenities=amenity)
                if facilities is not None:
                    for facility in facilities:
                        qs = qs.filter(facilities=facility)

                paginator = Paginator(qs, 5, orphans=1)
                page = int(request.GET.get("page", 1))
                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):
    """ EditRoomView Definition """

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:  # if user does not have ownership
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, RoomDetail):
    """ RoomPhotosView Definition """

    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:  # if user does not have ownership
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "You can't delete the photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    """ EditPhotoView Definition """

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)
    success_message = "Photo updated"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):
    """ AddPhotoView Definition """

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):
    """ CreateRoomView Definition """

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container md:w-1/2 lg:w-5/12 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
    {% include 'mixins/room/room_form.html' with form=form cta="Upload Photo" %}
</div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
Edit Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container md:w-1/2 lg:w-5/12 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
    {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}
</div>
{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container md:w-1/2 lg:w-5/12 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
    {% include 'mixins/room/room_form.html' with form=form cta="Create Room" %}
</div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked on_favs i18n %}

{% block page_title %}
{{room.name}}
{% endblock page_title %}

{% block content %}
<div class="container max-w-full h-50vh flex mb-16 -mt-12">
    <div class="h-full w-1/2 bg-cover bg-center" style="background-image: url({{room.get_first_photo}})"></div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_four_photos %}
        <div class="h-auto w-1/2 bg-cover bg-center border border-gray-500" style="background-image: url({{photo.file.url}})"></div>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between mb-8">
            <div class="mr-6">
                <h4 class="text-3xl font-medium mb-px break-words">{{room.name}}</h4>
                <span class="text-gray-700 font-light">{{room.city}}</span>
            </div>
            <a class="flex flex-col items-center" href="{{room.host.get_absolute_url}}">
                {% include "mixins/user_avatar.html" with user=room.host %}
                <span class="mt-2 text-gray-500 text-sm">{{room.host.first_name}}</span>
            </a>
        </div>
        {% on_favs room as on_favs_boolean %}
        {% if on_favs_boolean %}
        <a class="btn block bg-red-400 text-white cursor-pointer w-1/3" href="{% url 'lists:toggle-room' room.pk %}?action=remove">{% trans 'Remove from Favourites' %}</a>
        {% else %}
        <a class="btn block bg-blue-500 text-white cursor-pointer w-1/3" href="{% url 'lists:toggle-room' room.pk %}?action=add">{% trans 'Save to Favourites' %}</a>
        {% endif %}
        <div class="flex border-section">
            <span class="mr-5 font-light text-gray-700">{{room.room_type}}</span>
            <span class="mr-5 font-light text-gray-700">{{room.beds}} bed{{room.beds|pluralize}}</span>
            <span class="mr-5 font-light text-gray-700">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
            <span class="mr-5 font-light text-gray-700">{{room.baths}} bath{{room.baths|pluralize}}</span>
            <span class="mr-5 font-light text-gray-700">{{room.guests}} guest{{room.guests|pluralize}}</span>
        </div>
        <p class="border-section">{{room.description}}</p>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">Amenities</h4>
            <ul class="list-disc ml-5">
                {% for a in room.amenities.all %}
                <li class="mb-2">{{a}}</li>
                {% endfor %}
            </ul>
            {% if room.amenities.count == 0%}
            <span class="text-light text-gray-500">No amenities</span>
            {% endif %}
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">Facilities</h4>
            <ul class="list-disc ml-5">
                {% for f in room.facilities.all %}
                <li class="mb-2">{{f}}</li>
                {% endfor %}
            </ul>
            {% if room.facilities.count == 0%}
            <span class="text-light text-gray-500">No facilities</span>
            {% endif %}
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">House Rules</h4>
            <ul class="list-disc ml-5">
                {% for hr in room.house_rules.all %}
                <li class="mb-2">{{hr}}</li>
                {% endfor %}
            </ul>
            {% if room.house_rules.count == 0%}
            <span class="text-light text-gray-500">No house rules</span>
            {% endif %}
        </div>
        <div class="mt-8">
            <h4 class="font-medium text-2xl mb-5">Reviews</h4>
            <div class="flex items-center">
                <div class="flex items-center">
                    <i class="fas fa-star text-teal-500 mr-1"></i>
                    <span class="font-bold text-xl">{{room.get_total_rating}}</span>
                </div>
                <div class="h-5 w-px bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{room.reviews.count}}</span>
                    <span>review{{room.reviews.count|pluralize}}</span>
                </div>
            </div>
            <div>
                {% for review in room.reviews.all %}
                <div class="border-section">
                    <div class="mb-4 flex">
                        <div>
                            {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-12 h-12' text='text-xl' %}
                        </div>
                        <div class="flex flex-col ml-4">
                            <span class="font-medium">{{review.user.first_name}}</span>
                            <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                        </div>
                    </div>
                    <p>{{review.review}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="w-1/3">
        {% if room.host == user %}
        <a class="btn block bg-red-500 text-white" href="{% url 'rooms:edit' room.pk %}">Edit Room</a>
        {% else %}
        {% if not request.session.is_hosting %}
        {% for calendar in room.get_calendars %}
        <div class="mb-16">
            <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}} {{calendar.year}}</span>
            <div class="cal-grid mb-4">
                {% for day_of_week in calendar.day_names %}
                <span class="font-medium">{{day_of_week}}</span>
                {%endfor %}
            </div>
            <div class="cal-grid">
                {% for day in calendar.get_days %}
                {% if day.day == 0 %}
                <span></span>
                {% else %}
                {% is_booked room day as is_booked_bool %}
                {% if day.past or is_booked_bool %}
                <span class="rounded w-full text-center p-1 {% if day.isToday %}bg-gray-400 text-white{% else %}bg-gray-200 text-gray-400{% endif %}">{{day}}</span>
                {% else %}
                <a class="bg-gray-200 rounded w-full text-center p-1 text-gray-700 hover:bg-teal-400 hover:text-white hover:font-medium cursor-pointer" href="{% url 'reservations:create' room.pk day.year day.month day.day %}?days=1">{{day}}</a>
                {% endif %}
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <div class="btn bg-red-400 text-white cursor-pointer">Book your stay</div>
        {% endif %}
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container md:w-1/2 lg:w-5/12 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
    {% include 'mixins/room/room_form.html' with form=form cta="Update Room" %}

    <div class="w-full text-center mt-6">
        <a class="text-teal-500 font-mediu hover:underline" href="{% url 'rooms:photos' room.pk %}">Edit photos</a>
    </div>
</div>
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
Home
{% endblock page_title %}

{% block content %}
<div class="container mx-auto font-light pb-10">
    <div class="bg-blue-800 h-25vh mt-32 mb-24 -mx-4 rounded-lg bg-cover bg-center" style="background-image: url(https://images.unsplash.com/photo-1517446915321-65e972f1b494?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80)"></div>

    <div class="flex flex-wrap -mx-4 mb-6">
        {% for room in rooms %}
        {% include 'mixins/room_card.html' with room=room %}
        {% endfor %}
    </div>

    <div class="flex items-center justify-center">
        {% if page_obj.has_previous %}
        <a class="text-teal-500" href="?page={{page_obj.previous_page_number}}">
            <i class="fas fa-arrow-left fa-md align-text-bottom"></i>
        </a>
        {% endif %}

        <span class="mx-3 font-medium text-sm">
            {% blocktrans with current_page=page_obj.number total_pages=page_obj.paginator.num_pages %}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
        </span>

        {%if page_obj.has_next %}
        <a class="text-teal-500" href="?page={{page_obj.next_page_number}}">
            <i class="fas fa-arrow-right fa-md align-text-bottom"></i>
        </a>
        {% endif %}
    </div>

    {{now}}
</div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
{{room.name}} | Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col">
    <div class="mb-10">
        <a href="{% url 'rooms:add-photo' room.pk %}" class="btn bg-red-500 text-gray-200 block w-1/6 ml-auto mr-5 text-white">Upload Photo</a>
    </div>

    {% for photo in room.photos.all %}
    <div class="mb-8 border border-gray-400 p-6 flex justify-between">
        <div class="flex items-start">
            <img src="{{photo.file.url}}" class="w-32 h-32" />
            <span class="ml-5 text-lg">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col justify-around w-2/12">
            <a href="{% url 'rooms:edit-photo' room.pk photo.pk %}" class="btn bg-blue-700 text-gray-200">Edit</a>
            <a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="btn border border-red-500">Delete</a>
        </div>
    </div>
    {% endfor %}
    <div class="flex justify-center">
        <a class="text-teal-500 font-medium text-xl hover:underline" href="{% url 'rooms:edit' room.pk %}">Back to edit page</a>
    </div>
</div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}

{% block content %}
<form method="GET" action="{% url 'rooms:search' %}">
    {{form.as_p}}
    <button>Search</button>
</form>

<h3>Results</h3>
{% for room in rooms.object_list %}
<h3>{{room.name}}</h3>
{% endfor %}

<h5>
    {% if rooms.has_previous %}
    <a href="{{request.get_full_path}}&page={{rooms.previous_page_number}}">Previous</a>
    {% endif %}

    Page {{rooms.number}} of {{rooms.paginator.num_pages}}

    {%if rooms.has_next %}
    <a href="{{request.get_full_path}}&page={{rooms.next_page_number}}">Next</a>
    {% endif %}
</h5>

{% endblock content %}