config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:  # dev mode only
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("start/<int:host_pk>/<int:guest_pk>/", views.start_conversation, name="start"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]  # /

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.db.models import Q
from core import models as core_models
from users import models as user_models
from rooms import models as room_models


class BookedDay(core_models.AbstractTimeStampModel):
    """ BookedDay Model Definition """

    date = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.date)


class Reservation(core_models.AbstractTimeStampModel):
    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        user_models.User, related_name="reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        room_models.Room, related_name="reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            day_diff = end - start
            print(self.room.pk)
            is_booked = BookedDay.objects.filter(
                Q(reservation__room=self.room.pk)
                & Q(date__range=(start, end - datetime.timedelta(days=1)))
            ).exists()  # return True if it is booked
            if not is_booked:
                super().save(*args, **kwargs)
                for i in range(day_diff.days):
                    date = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(date=date, reservation=self)
        else:
            super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from rooms import models as room_models
from reviews import forms as reivew_forms
from users import mixins as user_mixins
from . import models as reservation_models


class CreateError(Exception):
    """ CreateError Definition """

    pass


@login_required
def create(request, room, year, month, day):
    days = int(request.GET.get("days", 1))
    try:
        date = datetime.datetime(year=year, month=month, day=day)
        room = room_models.Room.objects.get(pk=room)
        reservation_models.BookedDay.objects.get(date=date, reservation__room=room)
        raise CreateError()
    except room_models.Room.DoesNotExist:
        messages.error(request, "Cannot book the room")
        return redirect(reverse("core:home"))
    except reservation_models.BookedDay.DoesNotExist:
        check_out = date + datetime.timedelta(days=days)
        reservation = reservation_models.Reservation.objects.create(
            guest=request.user, room=room, check_in=date, check_out=check_out
        )  # succssefully booked
        if reservation.pk is not None:
            return redirect(
                reverse("reservations:detail", kwargs={"pk": reservation.pk})
            )
        else:
            messages.error(request, "Cannot book the room")
            return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))


class ReservationDetailView(user_mixins.LoggedInOnlyView, View):
    """ ReservationDetailView Definition """

    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = reservation_models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = reivew_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/reservation_detail.html",
            {"reservation": reservation, "form": form},
        )


@login_required
def edit_reservation(request, pk, verb):
    reservation = reservation_models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = reservation_models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = reservation_models.Reservation.STATUS_CANCELED
        reservation_models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/reservation_detail.html
{% extends "base.html" %}

{% block page_title %}
Reservation {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col">
    <div class="border-t border-l border-r bg-cover bg-center h-56 rounded" style="background-image: url({{reservation.room.get_first_photo}})"></div>
    <div class="flex flex-col items-start border">
        <div class="font-medium border-b py-8 px-5 w-full">
            {{reservation.check_in}} - {{reservation.check_out}} <span class="ml-5 {% if reservation.status == 'pending' %}text-yellow-500{% elif reservation.status == 'canceled' %}text-red-600{%else %}text-teal-600{% endif %}">{{reservation.get_status_display}}</span>
        </div>
        <span class="text-2xl p-5 border-b  w-full">
            {{reservation.room.name}}
        </span>
        <div class="flex p-5 border-b w-full">
            <div class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=reservation.room.host %}
                <span class="mt-2 text-gray-500 text-sm">{{reservation.room.host.first_name}}</span>
            </div>
            <div class="ml-5 flex flex-col">
                <span class="font-medium mb-px">Contact your Airbnb Host</span>
                <a class="font-medium text-teal-500" href="{% url 'conversations:start' reservation.room.host.pk reservation.guest.pk %}">Send a Message</a>
            </div>
        </div>


        <div class="py-10 px-5">
            {% if reservation.status != 'canceled' %}
            {% if reservation.status == 'confirmed' and reservation.is_finished %}
            <span class="font-medium text-2xl text-center w-ful block mb-5">Write your review</span>
            <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-2/3 mx-auto">
                {% csrf_token %}
                {{form}}
                <button type="submit" class="btn bg-red-400 text-white cursor-pointer mt-5">Submit Review</button>
            </form>
            {% else %}
            {% if reservation.status == 'pending' %}
            <a class="btn bg-red-400 text-white cursor-pointer block px-5 mb-5" href="{% url 'reservations:edit' reservation.pk 'cancel' %}">Cancel Reservation</a>
            {% if reservation.room.host == user %}
            <a class="btn bg-red-400 text-white cursor-pointer block px-5" href="{% url 'reservations:edit' reservation.pk 'confirm' %}">Confirm Reservation</a>
            {% endif %}
            {% endif %}
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}